name: Deploy EasyTix Application

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath, zip
          coverage: none

#      - name: Run Tests
#        run: vendor/bin/phpunit

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "→ Navigating to project directory..."
            cd /var/www/easytix

            echo "→ Pulling latest code from master..."
            git pull origin master

            echo "→ Setting permissions for ubuntu user (to avoid Composer errors)..."
            sudo chown -R $USER:$USER .

            echo "→ Installing PHP dependencies..."
            composer install --no-dev --optimize-autoloader

            echo "→ Running Laravel optimizations..."
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan optimize

            echo "→ Installing frontend dependencies and building assets..."
            npm install
            npm run build

            echo "→ Setting final permissions for web server..."
            sudo chown -R www-data:www-data storage bootstrap/cache vendor
            sudo chmod -R 775 storage bootstrap/cache vendor

            echo "✅ Deployment complete!"
